title: Ard Ray
email: ard.ray@bantiarna.com
description: >- 
  bantiarna.com - Ard Ray
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bantiarna.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ArdRay

# Build settings
markdown: kramdown
highlighter: rouge
include: ['_events']
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: posts/page:num/

# Minification
sass:
  style: compressed

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/albums"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
